.run-tests: &run-tests
  name: Run Tests
  image: python:3.8
  caches:
  - pip
  script:
    - python3 -m venv venv
    - source venv/bin/activate
    - pip3 install -r requirements.txt
    - pytest

.build-docker-image: &build-docker-image
  services:
    - docker
  name: Build Docker Image
  image: google/cloud-sdk:latest
  script:
    - echo "${DEPLOYMENT_SVC_ACCOUNT_KEY}" > /gcr.key
    - gcloud auth activate-service-account $DEPLOYMENT_SVC_ACCOUNT --key-file=/gcr.key
    - gcloud auth configure-docker --quiet
    - docker login -u "_json_key" -p "${GCR_JSON_KEY}" https://us.gcr.io
    - docker build --build-arg VERSION=${BITBUCKET_BUILD_NUMBER}-${BITBUCKET_COMMIT:0:7} -t us.gcr.io/travello-api/apiv2/${BITBUCKET_REPO_SLUG}:${BITBUCKET_BUILD_NUMBER} .
    # Docker image is also repeating actions from above
    - docker push us.gcr.io/travello-api/apiv2/${BITBUCKET_REPO_SLUG}:${BITBUCKET_BUILD_NUMBER}

.update-stage-cluster: &update-stage-cluster
  name: Update Stage Cluster
  image: google/cloud-sdk:latest
  deployment: staging
  script:
    - echo "${DEPLOYMENT_SVC_ACCOUNT_KEY}" > /gcr.key
    - gcloud auth activate-service-account $DEPLOYMENT_SVC_ACCOUNT --key-file=/gcr.key
    - gcloud auth configure-docker --quiet
    - gcloud container clusters get-credentials $STAGE_GCR_KUBE_FLAGS
    - kubectl config current-context | grep -e "$STAGE_CLUSTER_NAME" || exit 1 # check stage cluster
    - docker pull us.gcr.io/travello-api/apiv2/${BITBUCKET_REPO_SLUG}:${BITBUCKET_BUILD_NUMBER}
    - kubectl set image deployment/${STAGE_DEPLOYMENT:-$BITBUCKET_REPO_SLUG} ${STAGE_CONTAINER:-$BITBUCKET_REPO_SLUG}=us.gcr.io/travello-api/apiv2/${BITBUCKET_REPO_SLUG}:${BITBUCKET_BUILD_NUMBER}
    - timeout 360 kubectl rollout status deployment/${STAGE_DEPLOYMENT:-$BITBUCKET_REPO_SLUG} || exit 1
    - docker tag us.gcr.io/travello-api/apiv2/${BITBUCKET_REPO_SLUG}:${BITBUCKET_BUILD_NUMBER} us.gcr.io/travello-api/apiv2/${BITBUCKET_REPO_SLUG}:stage
    - docker push us.gcr.io/travello-api/apiv2/${BITBUCKET_REPO_SLUG}:stage
  services:
    - docker

.deploy-production: &deploy-production
  name: Update Production Cluster
  image: google/cloud-sdk:latest
  deployment: production
  script:
    - echo "${DEPLOYMENT_SVC_ACCOUNT_KEY}" > /gcr.key
    - gcloud auth activate-service-account $DEPLOYMENT_SVC_ACCOUNT --key-file=/gcr.key
    - gcloud auth configure-docker --quiet
    - gcloud container clusters get-credentials $PRODUCTION_GCR_KUBE_FLAGS
    - kubectl config current-context | grep -e "$PRODUCTION_CLUSTER_NAME" || exit 1 # check live cluster
    - docker pull us.gcr.io/travello-api/apiv2/${BITBUCKET_REPO_SLUG}:${BITBUCKET_BUILD_NUMBER}
    - kubectl set image deployment/${PRODUCTION_DEPLOYMENT:-$BITBUCKET_REPO_SLUG} ${PRODUCTION_CONTAINER:-$BITBUCKET_REPO_SLUG}=us.gcr.io/travello-api/apiv2/${BITBUCKET_REPO_SLUG}:${BITBUCKET_BUILD_NUMBER}
    - timeout 360 kubectl rollout status deployment/${PRODUCTION_DEPLOYMENT:-$BITBUCKET_REPO_SLUG} || exit 1
    - docker tag us.gcr.io/travello-api/apiv2/${BITBUCKET_REPO_SLUG}:${BITBUCKET_BUILD_NUMBER} us.gcr.io/travello-api/apiv2/${BITBUCKET_REPO_SLUG}:production
    - docker push us.gcr.io/travello-api/apiv2/${BITBUCKET_REPO_SLUG}:production
  services:
    - docker

pipelines:
  default:
    - step: *run-tests
    - step:
        <<: *build-docker-image
        trigger: manual
    - step: *update-stage-cluster

  branches:
    develop:
      - step: *run-tests
      - step: *build-docker-image
      - step: *update-stage-cluster
      - step: # production is only on develop, and then optional
          trigger: manual
          <<: *deploy-production
options:
  docker: true

