apiVersion: apps/v1
kind: Deployment
metadata:
  name: feed-deployment
spec:
  selector:
    matchLabels:
      app: feed-rank-service
  template:
    metadata:
      labels:
        app: feed-rank-service
    spec:
      containers:
      - name: feed-rank-service
        image: docker.io/nazib/rankalgorithm:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: testreg


---
apiVersion: v1
kind: Service
metadata:
  name: feed-service
spec:
  type: NodePort
  selector:
    app: feed-rank-service
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30001

