apiVersion: apps/v1
kind: Deployment
metadata:
  name: feed-rank-service-deployment
spec:
  selector:
    matchLabels:
      app: feed-rank-service
  template:
    metadata:
      labels:
        app: feed-rank-service
    spec:
      containers:
      - name: feed-rank-service
        image: gcr.io/cedar-talent-279001/feed-algorithm:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: feed-service
spec:
  type: ClusterIP
  selector:
    app: feed-rank
  ports:
  - port: 5000
    targetPort: 5000
