version: '2'
services:
  web:
    build: ./
    environment:
      PORT: "8080"
      FLASK_APP: app.py
      FLASK_ENV: development
    ports:
      - "8080:8080"
      - "6006:6006" # for tensorboard
    volumes:
      - ./:/app
    command:
      - bash
      - -c
      - |
        mkdir -p logs;
        cp -R -n ./base_data/logs/* ./logs/;
        python -m flask run --host=0.0.0.0 --port 8080;

  test:
    image: tensorflow/tensorflow:2.2.0
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - ./:/app
    working_dir: /app
    command:
      - bash
      - -c
      - |
        pip install -r requirements.txt;
        mkdir -p logs;
        cp -R -n ./base_data/logs ./;
        python;
