apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-http
spec:
  containers:
  - name: liveness
    image: us.gcr.io/travello-api/apiv2/${BITBUCKET_REPO_SLUG}:${BITBUCKET_BUILD_NUMBER}
    livenessProbe:
      httpGet:
        path: /health
        port: 5000
      initialDelaySeconds: 3
      periodSeconds: 3
