apiVersion: apps/v1
kind: Deployment
metadata:
  name: feedrank-deployment
spec:
  selector:
    matchLabels:
      app: feedrank
  template:
    metadata:
      labels:
        app: feedrank
    spec:
      containers:
      - name: feedrank
        image: gcr.io/cedar-talent-279001/feedrank
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env :
          - name : PORT
            value : "8080"
